version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongo
    restart: unless-stopped
    volumes:
      - illustry_mongo:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootPass
      MONGO_INITDB_DATABASE: illustry
    ports:
      - "27017:27017"
    networks:
      - illustry-network

  illustrybackend:
    build:
      context: ./  # Build context for backend
      dockerfile: backend/Dockerfile  # Optional, default is Dockerfile
    container_name: illustrybackend
    restart: unless-stopped
    environment:
      MONGO_URL: mongodb://mongo:27017/illustry
      MONGO_USER: root
      MONGO_PASSWORD: rootPass
      BACKEND_PORT: 7001
    ports:
      - "7001:7001"
    networks:
      - illustry-network

  illustryfrontend:
    build:
      context: ./  # Build context for frontend
      dockerfile: frontend/Dockerfile  # Optional, default is Dockerfile
    container_name: illustryfrontend
    restart: unless-stopped
    environment:
      NEXT_PUBLIC_BACKEND_PUBLIC_URL: http://illustrybackend:7001
    ports:
      - "3000:3000"
    networks:
      - illustry-network

  n8n:
    image: n8n-n8n:latest # Use your custom fork here
    container_name: n8n
    environment:
      N8N_PORT: 5678
      N8N_HOST: localhost
      N8N_PROTOCOL: http
      N8N_PUBLIC_API_URL: http://localhost:5678
      N8N_USER_MANAGEMENT_DISABLED: "true"
      N8N_BASIC_AUTH_ACTIVE: "false"
    ports:
      - "5678:5678"
    volumes:
      - n8n_data:/home/node/.n8n
    tmpfs:
      - /tmp  # Helps with performance & avoiding disk issues
    networks:
      - illustry-network

  openalexclassifier:
    image: openalex-topic-classifier:latest
    container_name: openalexclassifier
    restart: unless-stopped
    environment:
      PORT: 8080
      GUNICORN_WORKERS: 4
      PYTHONUNBUFFERED: "TRUE"
      PYTHONDONTWRITEBYTECODE: "TRUE"
      LOG4J_FORMAT_MSG_NO_LOOKUPS: "true"
    ports:
      - "8080:8080"
    command: serve
    networks:
      - illustry-network

networks:
  illustry-network:
    driver: bridge

volumes:
  illustry_mongo:
  n8n_data:
