# Deploy Astro Docs (monorepo) to GitHub Pages
name: Deploy Astro Docs to Pages

on:
  push:
    branches: ['main'] # Trigger workflow on pushes to the 'main' branch

  # Allows manual triggering from the Actions tab
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  build:
    name: Build Astro Docs Site
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Use the appropriate Node.js version

      # Install dependencies for the monorepo using Yarn
      - name: Install dependencies
        run: yarn install

      # Build the Astro docs site in the monorepo's `docs` package
      - name: Build Astro Docs site
        working-directory: packages/docs
        run: yarn build

      # Upload the build artifacts for deployment
      - name: Upload artifact for Pages deployment
        uses: actions/upload-pages-artifact@v2
        with:
          path: docs/dist

  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    needs: build
    steps:
      # Deploy the uploaded artifact to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
