name: Lerna Monorepo Build, Test, and Dependabot

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    name: Build Monorepo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Cache Yarn dependencies
        uses: actions/cache@v3
        with:
          path: .yarn/cache
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build TypeScript
        run: yarn build:ts

      - name: Check fs
        run: ls -alh 
        
      - name: Move build artifacts to separate folder
        run: mv ./build-output/ ./build-artifacts/

      - name: Compress Build Artifacts
        run: tar -czf build-artifacts.tar.gz build-artifacts/


      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: build-artifacts.tar.gz
          retention-days: 1

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: build
    services:
      mongodb:
        image: mongo:4.4.6
        env:
          MONGO_INITDB_ROOT_USERNAME: ${{ secrets.MONGO_INITDB_ROOT_USERNAME }}
          MONGO_INITDB_ROOT_PASSWORD: ${{ secrets.MONGO_INITDB_ROOT_PASSWORD }}
          MONGO_INITDB_DATABASE: illustrytest
        ports:
          - 27017:27017
        options: >-
          --health-cmd mongo
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - name: Install mongosh
        run: |
          sudo apt-get install gnupg
          wget -qO- https://www.mongodb.org/static/pgp/server-7.0.asc | sudo tee /etc/apt/trusted.gpg.d/server-7.0.asc
          echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/7.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-7.0.list
          sudo apt-get update
          sudo apt-get install -y mongodb-mongosh
          mongosh --version

      - name: Initialize MongoDB
        run: |
          mongosh --host localhost:27017 -u ${{ secrets.MONGO_INITDB_ROOT_USERNAME }} -p ${{ secrets.MONGO_INITDB_ROOT_PASSWORD }} --authenticationDatabase admin <<EOF
            db = db.getSiblingDB('illustrytest');
            db.createUser({ user: test, pwd: 'testPass', roles: [{ role: 'readWrite', db: 'illustrytest' }] });
            db.createCollection('dashboards');
            db.createCollection('visualizations');
            db.createCollection('projects');
          EOF

      - name: Download Build Artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts

      - name: Extract Build Artifacts
        run: tar -xzf build-artifacts.tar.gz

      - name: Run Tests
        run: yarn test

  dependabot:
    name: Dependabot Checks
    runs-on: ubuntu-latest
    needs: [build, test]
    steps:
      - name: Download Build Artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts

      - name: Extract Build Artifacts
        run: tar -xzf build-artifacts.tar.gz

      - name: Run Dependabot Updates
        run: yarn audit || echo "Dependabot passed"
